[33mWARNING [0m urllib3.connectionpool:connectionpool.py:745 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6F7672648>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c629f8019dec81aa04bae01ed97d1692/title
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:745 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6F75CEE48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c629f8019dec81aa04bae01ed97d1692/title
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:745 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6F75CE7C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c629f8019dec81aa04bae01ed97d1692/title